version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: github-repos-postgres
    environment:
      POSTGRES_DB: github_repos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - github-repos-network

  app:
    build: .
    container_name: github-repos-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/github_repos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - github-repos-network

volumes:
  postgres_data:

networks:
  github-repos-network:
    driver: bridge 