spring:
  application:
    name: repository-searcher
  datasource:
    url: jdbc:postgresql://localhost:5432/github_repos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

github:
  api:
    base-url: https://api.github.com
    timeout: 30000

logging:
  level:
    com.github.repositorysearcher: DEBUG
    org.springframework.web: DEBUG 